#!/bin/bash

function getJsonVal() {
python -c "import json,sys;sys.stdout.write(json.dumps(json.load(sys.stdin)$1))";
}

unset AWS_SECRET_ACCESS_KEY
unset AWS_ACCESS_KEY_ID
unset AWS_SESSION_TOKEN
unset AWS_EXPIRE
unset AWS_ENV


echo "Please enter AUTHENTICATOR TOKEN :"
read token

result=$(aws sts get-session-token --token-code $token  --serial-number arn:aws:iam::xxxxx:mfa/aaaa@hotmail.com --duration-seconds 129600 --profile g4hs)

AccessKeyId=$(echo $result | getJsonVal "['Credentials']['AccessKeyId']" | sed 's/"//g' )
SecretAccessKey=$(echo $result | getJsonVal "['Credentials']['SecretAccessKey']" | sed 's/"//g' )
SessionToken=$(echo $result | getJsonVal "['Credentials']['SessionToken']" | sed 's/"//g' )

export AWS_ACCESS_KEY_ID=$AccessKeyId
export AWS_SECRET_ACCESS_KEY=$SecretAccessKey
export AWS_SESSION_TOKEN=$SessionToken

echo export `env | grep AWS_ACCESS_KEY_ID` > ~/.aws/c
echo export `env | grep AWS_SECRET_ACCESS_KEY` >> ~/.aws/c
echo export `env | grep AWS_SESSION_TOKEN` >> ~/.aws/c
